"""add intake, media, case, camera tables

Revision ID: bc3c8316111d
Revises: 2b53a0b0946d
Create Date: 2026-07-08 14:59:59.890695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3c8316111d'
down_revision: Union[str, Sequence[str], None] = '2b53a0b0946d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_code', sa.String(length=32), nullable=False),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_devices_device_code'), 'camera_devices', ['device_code'], unique=True)
    op.create_table('intake_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_events_image_hash'), 'intake_events', ['image_hash'], unique=False)
    op.create_table('camera_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_device_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_device_id'], ['camera_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_api_keys_key_hash'), 'camera_api_keys', ['key_hash'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_no', sa.String(length=32), nullable=False),
    sa.Column('intake_event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('plate_no', sa.String(length=16), nullable=True),
    sa.Column('violation_type', sa.String(length=32), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_opinion', sa.String(length=512), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intake_event_id'], ['intake_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_no'), 'cases', ['case_no'], unique=True)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_event_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intake_event_id'], ['intake_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_cases_case_no'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_camera_api_keys_key_hash'), table_name='camera_api_keys')
    op.drop_table('camera_api_keys')
    op.drop_index(op.f('ix_intake_events_image_hash'), table_name='intake_events')
    op.drop_table('intake_events')
    op.drop_index(op.f('ix_camera_devices_device_code'), table_name='camera_devices')
    op.drop_table('camera_devices')
    # ### end Alembic commands ###
